# Generated by Django 5.2.1 on 2025-05-31 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='api_key',
        ),
    ]
