# Generated by Django 5.2.1 on 2025-06-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_provider_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('sendgrid', 'SendGrid')], default='twilio', max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
