# Generated by Django 5.2.1 on 2025-06-02 17:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0004_notification_error_message_notification_message_sid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="channel",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("email", "Email"),
                        ("sms", "SMS"),
                        ("push", "Push Notification"),
                        ("whatsapp", "WhatsApp"),
                    ],
                    max_length=50,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
