# Generated by Django 5.2.1 on 2025-06-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_provider_channel_alter_notification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
