# Generated by Django 5.2.1 on 2025-06-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
